<a href="https://colab.research.google.com/github/mahankali777/mahankali777/blob/main/Copy_of_Rainfall_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np
import pandas as pd

In [ ]:

dataset = pd.read_csv('weatherAUS.csv')
X = dataset.iloc[:,[1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]].values
Y = dataset.iloc[:,-1].values

In [ ]:
print(X)

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Sydney' 16.8 22.7 ... 20.1 22.0 'No']
 ['Sydney' 15.7 24.3 ... 21.2 22.3 'No']
 ['Sydney' 1.0 nan ... nan nan nan]]


In [ ]:
print(dataset.head())

         Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
1  2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2  2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   
3  2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN   
4  2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  Humidity3pm  \
0           W           44.0          W  ...        71.0         22.0   
1         WNW           44.0        NNW  ...        44.0         25.0   
2         WSW           46.0          W  ...        38.0         30.0   
3          NE           24.0         SE  ...        45.0         16.0   
4           W           41.0        ENE  ...        82.0         33.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7    

In [ ]:
dataset.drop(['Sunshine'],axis=1)

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
0      2008-12-01   Albury     13.4     22.9       0.6          NaN   
1      2008-12-02   Albury      7.4     25.1       0.0          NaN   
2      2008-12-03   Albury     12.9     25.7       0.0          NaN   
3      2008-12-04   Albury      9.2     28.0       0.0          NaN   
4      2008-12-05   Albury     17.5     32.3       1.0          NaN   
...           ...      ...      ...      ...       ...          ...   
32892  2015-10-07   Sydney     19.7     21.5       0.0         13.2   
32893  2015-10-08   Sydney     17.0     21.1       0.0          6.6   
32894  2015-10-09   Sydney     16.8     22.7       0.0          5.4   
32895  2015-10-10   Sydney     15.7     24.3       0.0          6.8   
32896  2015-10-11   Sydney      1.0      NaN       NaN          NaN   

      WindGustDir  WindGustSpeed WindDir9am WindDir3pm  ...  Humidity9am  \
0               W           44.0          W        WNW  ...         71.0   
1             WNW           44.0        NNW        WSW  ...         44.0   
2             WSW           46.0          W        WSW  ...         38.0   
3              NE           24.0         SE          E  ...         45.0   
4               W           41.0        ENE         NW  ...         82.0   
...           ...            ...        ...        ...  ...          ...   
32892         SSW           67.0        SSE         SE  ...         61.0   
32893         ENE           35.0        ESE          E  ...         53.0   
32894         ENE           43.0          N         NE  ...         51.0   
32895           E           24.0         SE          E  ...         62.0   
32896         NaN            NaN        NaN        NaN  ...          NaN   

       Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
0             22.0       1007.7       1007.1       8.0       NaN     16.9   
1             25.0       1010.6       1007.8       NaN       NaN     17.2   
2             30.0       1007.6       1008.7       NaN       2.0     21.0   
3             16.0       1017.6       1012.8       NaN       NaN     18.1   
4             33.0       1010.8       1006.0       7.0       8.0     17.8   
...            ...          ...          ...       ...       ...      ...   
32892         56.0       1029.6       1033.6       5.0       7.0     20.3   
32893         57.0       1038.8       1036.0       7.0       7.0     18.5   
32894         51.0       1034.4       1029.7       7.0       5.0     20.1   
32895         60.0       1028.9       1025.8       1.0       4.0     21.2   
32896          NaN          NaN          NaN       NaN       NaN      NaN   

       Temp3pm  RainToday  RainTomorrow  
0         21.8         No            No  
1         24.3         No            No  
2         23.2         No            No  
3         26.5         No            No  
4         29.7         No            No  
...        ...        ...           ...  
32892     19.0         No            No  
32893     19.9         No            No  
32894     22.0         No            No  
32895     22.3         No            No  
32896      NaN        NaN           NaN  

[32897 rows x 22 columns]

In [ ]:
print(Y)

['No' 'No' 'No' ... 'No' 'No' nan]


In [ ]:
Y = Y.reshape(-1,1)

In [ ]:

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
X = imputer.fit_transform(X)
Y = imputer.fit_transform(Y)

In [ ]:

print(X)

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Sydney' 16.8 22.7 ... 20.1 22.0 'No']
 ['Sydney' 15.7 24.3 ... 21.2 22.3 'No']
 ['Sydney' 1.0 25.0 ... 19.0 18.4 'No']]


In [ ]:

print(Y)

[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 ['No']]


In [ ]:

from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
X[:,0] = le1.fit_transform(X[:,0])
le2 = LabelEncoder()
X[:,4] = le2.fit_transform(X[:,4])
le3 = LabelEncoder()
X[:,6] = le3.fit_transform(X[:,6])
le4 = LabelEncoder()
X[:,7] = le4.fit_transform(X[:,7])
le5 = LabelEncoder()
X[:,-1] = le5.fit_transform(X[:,-1])
le6 = LabelEncoder()
Y[:,-1] = le6.fit_transform(Y[:,-1])

In [ ]:
print(X)

[[0 13.4 22.9 ... 16.9 21.8 0]
 [0 7.4 25.1 ... 17.2 24.3 0]
 [0 12.9 25.7 ... 21.0 23.2 0]
 ...
 [10 16.8 22.7 ... 20.1 22.0 0]
 [10 15.7 24.3 ... 21.2 22.3 0]
 [10 1.0 25.0 ... 19.0 18.4 0]]


In [ ]:
print(Y)

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


In [ ]:
Y = np.array(Y,dtype=float)
print(Y)

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


In [ ]:

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)


In [ ]:

print(X)

[[-1.57674374  0.0202209  -0.18652981 ... -0.16727363 -0.10364094
  -0.52744545]
 [-1.57674374 -1.01808324  0.18194861 ... -0.11087687  0.32752134
  -0.52744545]
 [-1.57674374 -0.06630445  0.28244273 ...  0.60348202  0.13780993
  -0.52744545]
 ...
 [ 1.60596151  0.60859324 -0.22002785 ...  0.43429175 -0.06914796
  -0.52744545]
 [ 1.60596151  0.41823748  0.04795646 ...  0.64107985 -0.01740849
  -0.52744545]
 [ 1.60596151 -2.12560766  0.16519959 ...  0.22750365 -0.69002164
  -0.52744545]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [ ]:

print(X_train)

[[ 0.33287941  0.81625407 -0.42101608 ...  0.35909608 -0.43132427
   1.89593066]
 [ 0.33287941  1.59498218  0.60067409 ...  1.84421061  0.43100028
  -0.52744545]
 [ 1.28769098  0.10674624  0.0814545  ... -0.01688228  0.2067959
  -0.52744545]
 ...
 [ 1.60596151  0.62589831  0.65092115 ...  0.88546579  0.93114852
   1.89593066]
 [ 0.65114993  0.47015269 -0.60525529 ...  0.09591123 -0.48306375
  -0.52744545]
 [-1.57674374 -0.84503255 -1.69394154 ... -1.55839357 -2.03524795
  -0.52744545]]


In [ ]:

print(Y_train)

[[1.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [1.]]


In [ ]:

from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=100,random_state=0)
classifier.fit(X_train,Y_train)

<ipython-input-23-84bb09ba651d>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  classifier.fit(X_train,Y_train)


RandomForestClassifier(random_state=0)

In [ ]:
classifier.score(X_train,Y_train)

0.9996200174791959

In [ ]:

y_pred = le6.inverse_transform(np.array(classifier.predict(X_test),dtype=int))
Y_test = le6.inverse_transform(np.array(Y_test,dtype=int))

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:155: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:

print(y_pred)

['Yes' 'No' 'Yes' ... 'No' 'Yes' 'No']


In [ ]:
print(Y_test)

['Yes' 'Yes' 'Yes' ... 'No' 'Yes' 'No']


In [ ]:

y_pred = y_pred.reshape(-1,1)
Y_test = Y_test.reshape(-1,1)

In [ ]:

df = np.concatenate((Y_test,y_pred),axis=1)
dataframe = pd.DataFrame(df,columns=['Rain on Tommorrow','Predition of Rain'])

In [ ]:

print(dataframe)

     Rain on Tommorrow Predition of Rain
0                  Yes               Yes
1                  Yes                No
2                  Yes               Yes
3                   No                No
4                   No                No
...                ...               ...
6575               Yes                No
6576                No                No
6577                No                No
6578               Yes               Yes
6579                No                No

[6580 rows x 2 columns]


In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,y_pred)

0.8530395136778115

end of code


In [ ]:

print(X_test[0])

[-0.62193216  0.81625407  0.24894469 -0.10617632 -0.4822945  -0.432468
  0.828948    0.37555125 -1.29848451 -0.81550248  1.05006396  2.14187756
 -0.04824399  0.00388102 -0.63879736 -0.67402635  0.71627552 -0.34509182
  1.89593066]


In [ ]:
# testing

c = [1.62193216 , -0.81625407 , 2.24894469 ,-0.10617632 ,-0.4822945,  -0.432468,
  0.828948,    0.37555125, -1.2988451, 7.8150248,  1.0506396,  2.1487756,
 5.0484399,  0.0038102, -0.6389736, -0.6740635,  0.7127552, -0.3409182,
  1.8959306]

c = np.array(c)

# Reshape the array
c = c.reshape(-1,19)


In [ ]:
l = classifier.predict(c)

In [ ]:
l

array([1.])